WIP RxJS Turn Indicator
angular-schule/website-articles pull request #11
Opened 2021-12-10 16:27 UTC by fmalcher

2021-12-12 13:26 UTC, d-koppenhagen requested changes

2021-12-12 13:26 UTC, d-koppenhagen commented on blog/2021-12-rxjs-turn-signal/README.md
> +As you can see, the release is not captured on the button but on the whole document instead.
Im Beispiel ist das aber nicht auf dem gesamten Dokument, sondern schon auf dem Button.
Siehe Suggestion zuvor.

2021-12-12 13:26 UTC, d-koppenhagen commented on blog/2021-12-rxjs-turn-signal/README.md
> +The release event is then not emitted on the button but wherever the mouse is at that moment.
Klingt etwas doppelt verglichen mit Zeile 86

2021-12-12 13:26 UTC, d-koppenhagen commented on blog/2021-12-rxjs-turn-signal/README.md
> +As a the notifier we use an Observable that emits after 5100 ms (using `timer()` with just 1 argument creates an Observable that fires once and then completes).
```suggestion
As the notifier we use an Observable that emits after 5100 ms (using `timer()` with just one argument creates an Observable that fires once and then completes).
```

2021-12-12 13:26 UTC, d-koppenhagen commented on blog/2021-12-rxjs-turn-signal/README.md
> +
```suggestion
For the trigger release, we have already created the necessary event stream `release$`, so we have the two parts ready to be combined.

### Creating the notifier

As described before, to create our closing notifier we have to wait for

```

2021-12-12 13:26 UTC, d-koppenhagen commented on blog/2021-12-rxjs-turn-signal/README.md
> +const release$ = fromEvent(triggerBtn, 'mouseup');
```suggestion
const release$ = fromEvent(document, 'mouseup');
```

2021-12-13 10:35 UTC, JohannesHoppe requested changes

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +First things first, let's take a look at the original car behavior.
```suggestion
First things first, let's take a look at the original behaviour of the circuit in the car.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +It was an older car, so the handle next to the steering wheel is nothing more than an on/off switch which can be locked in the end position.
```suggestion
Modern cars have a crazy number of buttons, but setting a turn signal is still basically the same. The handle next to the steering wheel is nothing more than an on/off switch which can be locked in the end position.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +That means, if I just softly push the trigger, the turn signal outputs 3 on/off cycles.
Oben: "if you", hier "If I"

```suggestion
That means, if you just softly push the trigger, the turn signal outputs 3 on/off cycles.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +When I lock the trigger and instantly pull it back, the signal performs 3 cycles as well.
```suggestion
If you lock the trigger, the signal is repeated until you pull the trigger back.
When you lock the trigger and pull it back immediately, the signal performs 3 cycles as well.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +
Bonus-Punkte: hier ein Marble-Diagram

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +As you can see, the release is not captured on the button but on `document` instead.
```suggestion
As you can see, we have decided to capture the release event not on the button but on `document`.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +This is an important detail: You can move the mouse away from the button while it is pressed, and the event will be fired somewhere else.
```suggestion
This is an important detail: You can now accidentally move the mouse away while the mouse button is still pressed. Nevertheless, we do not miss the important release event, which might be fired somewhere else.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +- **`exhaustMap`** is one of the less commonly used operators: As long as an inner subscription is running, all other incoming requests will be ignored. That means, if we press the button while a sig
```suggestion
- **`exhaustMap`** is one of the less commonly used operators: As long as an inner subscription is running, all other incoming requests will be ignored. That means, if we press the button while a signal is running, nothing will happen. There is no queue like with `concatMap` but all incoming events will be ignored.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +Back to our turn signal, things become a bit more sophisticated.
```suggestion
Back to our turn signal, now things become a little more challenging.
```

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +
Hier bitte nochmal der volle Quelltext rein. Wenn der Stackblitz link mal irgendwann nicht mehr geht, dann ist die Info weg. Und nur Github-Zeugs kommt in den GitHub Arctic Code Vault – denk an die Menschheit in 10.000 Jahren! 😉

2021-12-13 10:35 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +
+ kleiner Abschluss hier. Beispiel:

```suggestion
Have you enjoyed this article? Then please share it in your network! Do you know another interesting circuit? Then write to us and maybe we will also implement this case with RxJS! 
```

2021-12-13 10:36 UTC, JohannesHoppe commented on blog/2021-12-rxjs-turn-signal/README.md
> +
Bei den anderen auch, sorry! 😇

2021-12-13 13:41 UTC, merged